### PR TITLE
Clone, restructure, continuous interrupt read 

### PR DESCRIPTION
**Pull request by reinismu**
* Use `=1.0.0-alpha.10` as `esp-idf-hal` doesn't support version 11 yet :/
* Ability to Clone `GenericUid`
* Remove chip communication part from `new`. When I use it it seems easier to keep all init logic in its own method. In this case `initialize_chip`
* Read all interrupts in one go. That's what Data sheet asks to do to avoid race conditions as reading first interrupt will clear all of them
* Start interrupt waiting with delay as otherwise it will fail first time. Reduces communication

### CODE REVIEW

**Comment by jspngh** [comment]
Looks good. I would like to rebase this on the latest master though, to only keep the 1 commit with new changes.
I can do the rebase and push it, or you can do it if you want.

**Comment by reinismu** [comment]
image
This should work right?

**Comment by jspngh** [comment]
That will create one commit, so that's already better than merging all 14 commits.
But the commit message will be the combination of the messages of the 14 commits, many of which are not relevant for these changes.
Do you mind if I push the rebased version of this branch?

**Comment by reinismu** [comment]
Thought it will use PR name for commit. Sure feel free to make rebase it :)

**Review by jspngh — APPROVED** [review]

**Pull request merged**
